server:
  port: 8081

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database: MYSQL
    show-sql: true
  sql:
    init:
      platform: mysql
  datasource:
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}





